### ISSUE TITLE
Where do Identities appear?

### ISSUE THREAD

**Issue by gorenje** [fastmail/JMAP-Samples#11]
Hi There!

I've managed to create Identities using the JMAP API. As basis, I've used the python3 example in this repo.

What I did was replace the create_res call in the example with the following bit of code:
```
create_res = client.make_jmap_call(
    {
        "using": [
            "urn:ietf:params:jmap:core",
            "urn:ietf:params:jmap:mail",
            "urn:ietf:params:jmap:submission",
        ],
        "methodCalls": [
           [ "Identity/set", {
               "accountId": account_id,
               "forbiddenFrom": False,
               "create": { "fubar": {
                   'bcc': None,
                   'email': 'fubar@XXX.org',
                   'htmlSignature': '',
                   'name': 'MyName',
                   'replyTo': None,
                   'textSignature': ''
               }}
           }, "howzats" ],
           [ "Identity/get", {
               "accountId": account_id,
           } , "pluckaduck"]
        ]
    }
)
```

The identity is actually created and the get request lists the new identity, but now my question: where do I see the new identity in the Fastmail web interface? I've looked in Settings --> Users & Aliases which actually does list the identities that I've created through the web interface but not those created via JMAP API.

**Comment by gorenje** [comment]
Just found them when composing an email - they appear in the dropdown for the sender. They don't appear in the Settings >> "Users & Aliases" - I assume that identities != aliases.

**Comment by neilj** [comment]
Identities in Fastmail can be configured in [Settings → Sending Identities](https://www.fastmail.com/settings/identities).

**Comment by gorenje** [comment]
👍 Just found it - sorry for the confusion!
