### ISSUE TITLE
.NET JMAP Library

### ISSUE THREAD

**Issue by tirth** [fastmail/JMAP-Samples#19]
Hi there - I recently stumbled across JMAP, and as a fan of well-designed APIs and my Fastmail account, I had to take the opportunity to muck around a little bit.

Unfortunately, I couldn't find any .NET libraries for it, so then I had to [make one](https://github.com/tirth/JmapNet).

Would you be interested in a pull request with a sample?

**Comment by tjwds** [comment]
Hey @tirth!  Yes, we would definitely welcome a PR with samples.  For each of the languages we provide samples for, we've attempted to demonstrate roughly the same programs; please let us know if you'd like us to concretely specify this!  I'm going to go ahead and close this issue, but feel free to reach out if you have any questions.  Thanks!
