### ISSUE TITLE
Disallowed capabilities: urn:ietf:params:jmap:contacts

### ISSUE THREAD

**Issue by FAE56** [fastmail/JMAP-Samples#22]
I paied for a standard plan and use a api token to request the JMAP api.
But I'm not allowed to use the contacts capability.
How to get the contacts capability?

**Comment by rsto** [comment]
Currently we do not support that capability for integration. We plan to support it next year.

If you haven't seen, please check our Developer page how to integrate with our JMAP Email API: https://www.fastmail.com/developer/integrating-with-fastmail/

There's also our public JMAP Topicbox group where we happily talk anything about JMAP: https://jmap.topicbox.com/
