### ISSUE TITLE
How to use results in complex queries

### ISSUE THREAD

**Issue by rsalesas** [fastmail/JMAP-Samples#24]
I'm trying to create a set of methodCalls that retrieve some mailboxes, retrieve message ids that match the criteria, and then change the labels for the messages. If I do each step separately, and store the results, it works fine (that is I retrieve the mailbox id through a method call, then retrieve the email ids, then set the labels, each with separate calls to the server). There's obviously something basic I'm missing, and I've read all the docs and the samples (all the samples do simple things like retrieving a list of IDs).

This is the code I have so far, I haven't added changing the labels yet. But even this doesn't work beyond the first method call to retrieve the mailbox ids. 

```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail"
  ],
  "methodCalls": [
        [
      "Mailbox/query",
      {
        "accountId": “xxx”,
        "filter": {
          "role": "inbox"
        }
      },
      "inbox"
    ],
    
    [
      "Mailbox/query",
      {
        "accountId": “xxx”,
        "filter": {
          "role": "archive"
        }
      },
      "archive"
    ],

    [
      "Email/query",
      {
        "accountId": “xxx”,
        "filter": {
          "#inMailbox": {
            "resultOf": "inbox",
            "name": "Mailbox/query",
            "path": "/ids"
          },
          "before": "2023-01-01T01:17:02Z"
        }
      },
      "messages"
    ],
    
    [
      "Email/set",
      {
        "accountId": “xxx”,
        "update": {
          "#ids": {
            "resultOf": "messages",
            "name": "Email/query",
            "path": "/ids"
          }
        }
      },
      "null"
    ]
  ]
}
```

**Comment by rjbs** [comment]
The short version of the answer is:  "#foo" arguments for backreferences only works at the top level.  So this could work:

```json
[ "Method/call", { "#arg": { "resultOf": "x", "name": "y", "path": "/z" } }, "a" ]
```

But this cannot:

```json
[ "Method/call", { "foo": { "#nested": { "resultOf": "x", "name": "y", "path": "/z" } } }, "a" ]
```

This is just how backreferences work.  Sometimes we've talked about an extension to provide more extensive backreferences, but the line had to be drawn somewhere, and it's there: at the top level of arugments.

**Comment by rsalesas** [comment]
OK, I don't think I read that anywhere in the documentation. Would be good to add it. I got it now.
