### ISSUE TITLE
Sample for EventSource connection to Fastmail?

### ISSUE THREAD

**Issue by amyreese** [fastmail/JMAP-Samples#7]
Hey folks,

I'm working on a JMAP client for Python that uses AsyncIO, following the specs at https://jmap.io/spec-core.html. I've got the JMAP portion of the API functioning, and I can use that to fetch mailboxes and emails from my personal account. However, when trying to connect to the EventSource URL and stream changes, I always get a 401 Unauthorized error, with "Incorrect username or password."

I'm using the same HTTP client/auth parameters that I use for connections to the JMAP API, and the spec does not mention anything about authentication specific to the EventSource API. Is there a different authentication standard necessary for EventSource connections, or is this something that's not supported for third party applications with Fastmail?

**Comment by jreese** [comment]
Relevant code at https://github.com/jreese/jaymap/blob/main/jaymap/client.py#L107 if that helps.

**Comment by rjbs** [comment]
Heya.  Unfortunately, Fastmail's EventSource doesn't allow non-Fastmail clients to connect, yet.  The story behind this is sort of tedious and stupid, boiling down to "updating the EventSource server for this kind of auth was a pain."  Fortunately, our pain is coming to an end, and yours might be, too.  Very soon we'll be deploying some overhauled code for our push notifications, and it should make fixing this much simpler.

I don't have a timeline, but getting this out the door is important to me.  Not this week, but should be in the next few months.

**Comment by jreese** [comment]
Thank you for the response. So, just to be clear, the only option for receiving pushed changes in third party clients is to use the PushSubscription API with public URLs?

**Comment by neilj** [comment]
@jreese Unfortunately Fastmail hasn't implemented the PushSubscription part of the API yet either. This is also something we intend to do but haven't yet got to.

**Comment by 1player** [comment]
Any update? I've just spent a few days writing a Fastmail/JMAP notifier for Linux, and I'm saddened to find out both the event source and the websocket methods of getting Push updates aren't available. I guess the project's on hold until non-Fastmail clients can access the event source.

**Comment by rjbs** [comment]
Hey, as of today, you can create personal API tokens on beta.fastmail.com, which *will* work to get you an EventSource connection.  PushSubscription support is on the road map, but the timeline isn't rock solid yet.

**Comment by rjbs** [comment]
This hit production a few weeks ago, and so I'm closing this issue.  I'm hoping for PushSubscriptions in early 2023.

**Comment by rockorager** [comment]
Hey, sorry to bring up an old issue but I came across this today. I connected to the fastmail eventsource URL and was curious about the data received. It doesn't seem to follow the JMAP spec, and I was wondering if that is intentional?

There are two key differences:

[Spec](https://jmap.io/spec-core.html#the-statechange-object) requires @type to be, well, "@type" and contain the string "StateChange". The event I received has the key "type" which appears to be a type of state change.

Any insight would be appreciated, thanks!

Spec: 
```json
{
  "@type": "StateChange",
  "changed": {
    "a3123": {
      "Email": "d35ecb040aab",
      "EmailDelivery": "428d565f2440",
      "CalendarEvent": "87accfac587a"
    },
    "a43461d": {
      "Mailbox": "0af7a512ce70",
      "CalendarEvent": "7a4297cecd76"
    }
  }
}
```

Actual:
```
{
  "changed": {
    "a3123": {
      "Email": "redacted",
      "EmailDelivery": "redacted",
      "Mailbox": "redacted",
      "Thread": "redacted"
    }
  },
  "type": "connect"
}
```

**Comment by rockorager** [comment]
> You have found a bug. We'll look into it, thanks.

Thanks for looking into it! I also noticed the `ping` and `closeAfterState` URL params don't seem to change the behavior in any way.
