### ISSUE TITLE
Is there a full API list available?

### ISSUE THREAD

**Issue by 0x53A** [fastmail/JMAP-Samples#8]
Hi, today is the first time I've even heard of JMAP.

Is there a full list of APIs / endpoints / nodes / whatever it's called in JMAP terminology __implemented by fastmail__ available?
The second part is important, since it seems like FM implements a subset of the JMAP Email spec, e.g. https://github.com/fastmail/JMAP-Samples/issues/7#issuecomment-815363043

Specifically, I'd like to programmatically create labels and rules.

**Comment by neilj** [comment]
Hi Lukas. Fastmail's public JMAP API endpoint implements all of the standardised JMAP (i.e. [RFC8620](https://www.rfc-editor.org/rfc/rfc8620.html) and [RFC8621](https://www.rfc-editor.org/rfc/rfc8621.html)) except for PushSubscription and the event source endpoint. You can use this to programatically create labels (this is the Mailbox object in JMAP), but there's no standard API for rules at the moment. Opening up our custom JMAP extensions (including our Rule data type) is something we'd like to do eventually but I can't promise a timeline at this stage.
