### ISSUE TITLE
302 redirect

### ISSUE THREAD

**Issue by jsolarz** [fastmail/JMAP-Samples#9]
Hi,

I'm trying to build a mini test app to connect to fastmail via jmap using c#. I'm having an issue when I try to get a session with a 401 unauthorized. After debugging and profiling a bit, it seems pointing to https://jmap.fastmail.com/.well-known/jmap after authentication is redirecting to /session and I get a 302 redirect response.

I tried to replicate with postman but I can authenticate just fine.

Can anyone seems to identify the issue?

Here's a sample code:

HttpClient _client = new HttpClient(new HttpClientHandler() { AllowAutoRedirect = false });
_client.DefaultRequestHeaders.Clear();
_client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Helpers.Base64Encode($"{WellKnownKeys.FASTMAIL_USER}:{WellKnownKeys.FASTMAIL_PASSWORD}"));
var response = await _client.GetAsync(WellKnownKeys.FASTMAIL_JMAP_SERVER);

PS: Pointing directly to /session returns a session without issues.

Thanks

**Comment by neilj** [comment]
I suspect `AllowAutoRedirect = false` is your problem. From [the specification](https://datatracker.ietf.org/doc/html/rfc8620#section-2.2):

> The JMAP Session resource is then `https://${hostname}[:${port}]/.well-known/jmap` (following any redirects).

So you need to follow any redirects from the well-known path.
